language: python

python:
  - "2.7"

env:
  - AVRO=avro
  - AVRO=pyavroc

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

cache: pip

addons:
  apt:
    packages:
      - build-essential
      - gfortran
      - git
      - libblas-dev
      - libfftw3-dev
      - liblapack-dev
      - libtiff-dev
      - maven
      - swig

before_install:
  - pip install --upgrade pip
  - pip install numpy
  - pip install scipy
  - pip install flake8
  - pip install libtiff
  - pip install matplotlib
  - bash .travis/install_avro.sh "${AVRO}"
  - bash .travis/install_wndcharm.sh

install:
  - python setup.py install

before_script:
  - mvn checkstyle:check
  - flake8 -v .

script:
  - mvn test
  - python test/all_tests.py
  - ./test/integration/run_local_features
